### ISSUE TITLE
On Firefox there seems to be a small formatting issue at ( Bibliographic Notes)

### ISSUE THREAD

**Issue by 0bserver07** [distillpub/post--ctc#26]

**Comment by ludwigschubert** [comment]
Thanks for your report!
The section looks fine to me on Firefox 56. Could you post a screenshot and the version of Firefox you are using?

![screen shot 2017-11-27 at 2 21 45 pm](https://user-images.githubusercontent.com/1167977/33292530-6e0b0cb2-d37e-11e7-8362-e5b2cf9ccc19.png)

**Comment by 0bserver07** [comment]
It might be the issue with Firefox Quantum 57.0

![img](https://i.imgur.com/NFRjqDv.png)

**Comment by ludwigschubert** [comment]
Thanks @0bserver07! This indeed looks like an issue with CSS grid support. Unfortunately I can not reproduce on Firefox 57.0:

![screen shot 2017-11-27 at 3 13 45 pm](https://user-images.githubusercontent.com/1167977/33294530-e80c708a-d385-11e7-8df0-5c3dbd0bb656.png)

I will be [overhauling our polyfills](https://github.com/distillpub/template/issues/66) anyway and will keep an eye on Firefox support during that!

Until then, I can only ask you the usual suspects: what OS are you on, are you sure a reload doesn't help (I know how this sounds… but currently polyfills are loaded externally, so it could actually resolve the issue.), etc.

**Comment by 0bserver07** [comment]
No worries, it's very minor : ) Must be something with my Firefox setup on Ubuntu, will close the issue now.
