### ISSUE TITLE
"!" in main figure

### ISSUE THREAD

**Issue by davidsteinar** [distillpub/post--ctc#33]
Maybe this is considered nitpicking, but CTC would never predict "!" as in "hello!" or "world!" as used in the first figure. An exclamation mark is not a phoneme.

**Comment by awni** [comment]
Actually a lot of CTC based speech recognizers are grapheme based. Checkout [Deep Speech](https://arxiv.org/abs/1412.5567) for example. Although to be fair, the output set doesn't include `!`.
 
In general, CTC makes no assumptions about the output set, you could try any tokenization of the output you like.
